  registerCommunityWikiLeadProfiles();
  registerPinterestSearchProfile();
  registerTikTokProfile();
  registerEbaySearchProfile();
  registerGlassdoorProfiles();
  registerMediaCommerceLeadProfiles();
  registerNewsHomepageProfiles();
  registerPolishPortalProfiles();
  registerZeitProfiles();
  registerBookingProfiles();
  registerAcademicPublisherProfiles();
  registerAcademicPreprintProfiles();
  registerHostAwareProfile(true, hatenaBlogContent);
  registerHostAwareProfile(true, scientificRecordContent);
  registerCsdnProfiles();
  registerSubstackProfiles();
  registerPackageRegistryProfiles();
  registerStatuspageProfiles();
  registerLegalReferenceProfiles();
  registerHostAwareProfile(/(^|\.)sec\.gov$/i, secEdgarFilingContent);
  registerHostAwareProfile(true, institutionalPlatformContent);
  registerWykopProfiles();
  registerHostAwareProfile(true, docsHostContent);
  registerRailsRdocProfiles();
  registerRepoHostProfiles();
  registerGitHubThreadProfiles();
  registerHostAwareProfile(true, genericDocsSystemContent);
  registerCommunityWikiProfiles();
  registerHackerNewsProfiles();
  registerMastodonProfiles();
  registerDiscourseProfiles();
  registerRedditProfiles();
  registerStackOverflowProfiles();
  registerBehanceProfiles();
  registerInstagramProfiles();
  registerFacebookProfiles();
  registerTelegramProfiles();
  registerTwitterProfiles();
  registerThreadsProfiles();
  registerLinkedinProfiles();
  registerBlueskyProfiles();
  registerQuoraProfiles();
