  registerCommunityWikiLeadProfiles();
  registerPinterestSearchProfile();
  registerTikTokProfile();
  registerEbaySearchProfile();
  registerGlassdoorProfiles();
  registerRingierAxelSpringerProfiles();
  registerMediaCommerceLeadProfiles();
  registerNewsHomepageProfiles();
  registerWpHomepageProfile();
  registerOnetHomepageProfile();
  registerZeitProfiles();
  registerBookingProfiles();
  registerAcademicPublisherProfiles();
  registerAcademicPreprintProfiles();
  registerHostAwareProfile(true, hatenaBlogContent);
  registerHostAwareProfile(true, scientificRecordContent);
  registerCsdnProfiles();
  registerSubstackProfiles();
  registerPackageRegistryProfiles();
  registerStatuspageProfiles();
  registerLegalReferenceProfiles();
  registerHostAwareProfile(/(^|\.)sec\.gov$/i, secEdgarFilingContent);
  registerHostAwareProfile(true, institutionalPlatformContent);
  registerWykopProfiles();
  registerHostAwareProfile(true, docsHostContent);
  registerRailsRdocProfiles();
  registerRepoHostProfiles();
  registerGitHubThreadProfiles();
  registerGitHubPullResourceProfiles();
  registerGitLabThreadProfiles();
  registerGitLabMergeRequestResourceProfiles();
  registerGiteaFamilyPullResourceProfiles();
  registerGiteaFamilyThreadProfiles();
  registerBitbucketCloudPullStatusProfiles();
  registerBitbucketCloudPullResourceProfiles();
  registerBitbucketCloudThreadProfiles();
  registerPagurePullRequestProfiles();
  registerPagureThreadProfiles();
  registerSourcehutTodoThreadProfiles();
  registerSourcehutListsPatchsetProfiles();
  registerSourcehutListsArchiveThreadProfiles();
  registerAzureDevopsPullRequestProfiles();
  registerGerritFileResourceProfiles();
  registerGerritChangeProfiles();
  registerHostAwareProfile(true, genericDocsSystemContent);
  registerCommunityWikiProfiles();
  registerHackerNewsProfiles();
  registerMastodonProfiles();
  registerDiscourseProfiles();
  registerRedditProfiles();
  registerStackOverflowProfiles();
  registerBehanceProfiles();
  registerInstagramProfiles();
  registerFacebookProfiles();
  registerTelegramProfiles();
  registerTwitterProfiles();
  registerThreadsProfiles();
  registerLinkedinProfiles();
  registerBlueskyProfiles();
  registerQuoraProfiles();
