function pagureIssueRoute() {
  var match = (location.pathname || "").match(/^\/(.+)\/issue\/(\d+)\/?$/);
  if (!match) return null;

  var parts = match[1].split("/").filter(Boolean);
  if (!parts.length || parts.some(function(part) { return !/^[\w.%+~-]+$/.test(part); })) return null;

  var projectPath = parts.join("/");
  return {
    projectPath: projectPath,
    community: safeDecodeURI(projectPath),
    number: match[2],
    basePath: "/" + projectPath,
    issuePath: "/" + projectPath + "/issue/" + match[2]
  };
}

function pagureIssueRoot() {
  return document.querySelector(".repo-body-container") ||
    document.querySelector("main") ||
    (document.querySelector("#original_comment_box") || {}).parentElement;
}

function pagureIssueHeading(root, route) {
  return Array.prototype.slice.call(root.querySelectorAll("h1, h2, h3, h4")).find(function(heading) {
    return new RegExp("^#" + route.number + "(?:\\s|$)").test(normalizeText(heading.textContent));
  }) || null;
}

function pagureAssetEvidence() {
  var assets = Array.prototype.slice.call(document.querySelectorAll("script[src]")).map(function(script) {
    var value = script.getAttribute("src");
    if (!value) return null;
    try {
      var url = new URL(value, location.href);
      return url.origin === location.origin
        ? { pathname: url.pathname, search: url.search }
        : null;
    } catch (_error) {
      return null;
    }
  }).filter(Boolean);
  var paths = new Set(assets.map(function(asset) { return asset.pathname; }));
  return assets.some(function(asset) {
    return /\/static\/(?:pagure-common|pagure-relative-dates)\.js$/i.test(asset.pathname) &&
      /(?:^|[?&])pagure(?:=|&|$)/i.test(asset.search);
  }) || (paths.has("/static/comments.js") && paths.has("/static/reactions.js"));
}

function pagureProjectLink(route, suffix) {
  var path = route.basePath + (suffix || "");
  return Array.prototype.slice.call(document.querySelectorAll("a[href]")).find(function(link) {
    try {
      var url = new URL(link.getAttribute("href"), location.href);
      return url.origin === location.origin && url.pathname.replace(/\/$/, "") === path;
    } catch (_error) {
      return false;
    }
  }) || null;
}

function pagureProjectNavigation(route) {
  return !!(pagureProjectLink(route, "") && pagureProjectLink(route, "/issues"));
}

function pagureProductMatch(route, root) {
  if (!route || !root || !pagureAssetEvidence() || !pagureProjectNavigation(route)) return false;
  var opening = root.querySelector("#original_comment_box #comment-0, #comment-0.issue_comment");
  return !!(opening && root.querySelector("#comments") && pagureIssueHeading(root, route));
}

function pagureIssueBody(node) {
  if (!node) return null;
  if (node.matches && node.matches(".comment_text.comment_body, .comment_body, .autogenerated-comment")) return node;
  return node.querySelector(".comment_text.comment_body, .comment_body, .autogenerated-comment");
}

function pagureNodeMarkdown(node) {
  var body = pagureIssueBody(node);
  if (!body) return "";
  var clone = visibilityPrunedClone(body);
  removeAll(clone, "button, form, [role='tooltip'], .issue_actions, .issue_reactions, .comment-reactions");
  return cleanupMarkdownNoise(markdownFor(clone.innerHTML));
}

function pagureIssueAuthor(node) {
  var eventAuthor = normalizeText(node && node.textContent).match(/(?:from|by)\s+@([\w.-]+)/i);
  if (eventAuthor) return eventAuthor[1];
  var author = node && node.querySelector(".card-header .font-weight-bold, .font-weight-bold, [data-testid='author']");
  if (author) return normalizeText(author.getAttribute("title") || author.textContent);
  return "";
}

function pagureIssueTimestamp(node) {
  var time = node && node.querySelector("time[datetime]");
  return normalizeText(time && time.getAttribute("datetime"));
}

function pagureIssuePermalink(node, route) {
  var target = node && node.matches("[id^='comment-']")
    ? node
    : node && node.querySelector("[id^='comment-'], a[href*='#comment-']");
  var value = target && (target.id ? "#" + target.id : target.getAttribute("href"));
  var url = materializedHttpUrl(value);
  if (!url) return null;
  try {
    var parsed = new URL(url);
    if (parsed.origin !== location.origin || parsed.pathname.replace(/\/$/, "") !== route.issuePath) return null;
    return /^#comment-\d+$/.test(parsed.hash) ? parsed.href : null;
  } catch (_error) {
    return null;
  }
}

function pagureIssueInventory(route) {
  var api = location.origin + "/api/0" + route.basePath + "/issue/" + route.number + "?comments=true";
  var entries = [
    { label: "Project", url: location.origin + route.basePath },
    { label: "Issues", url: location.origin + route.basePath + "/issues" },
    { label: "Issue page", url: location.origin + route.issuePath },
    {
      label: "Issue API",
      url: api,
      detail: "When enabled, this includes comments. Static archives and some installations may not expose this route."
    }
  ];
  if (pagureProjectLink(route, "/pull-requests")) {
    entries.splice(2, 0, { label: "Pull requests", url: location.origin + route.basePath + "/pull-requests" });
  }
  return browsableInventory("Browse this Pagure issue", entries);
}
