function pagurePullRequestRoot() {
  return document.querySelector("#pr-wrapper");
}

function pagurePullRequestTitle(route, metadata) {
  var heading = pagurePullRequestHeading(route);
  var primary = heading && heading.querySelector(":scope > div:first-child");
  var values = primary && Array.prototype.slice.call(primary.querySelectorAll(".font-weight-bold")).map(function(node) {
    return normalizeText(node.textContent);
  });
  var title = values && values.find(function(value) { return value && value !== "#" + route.number; });
  return title || normalizeText(metadata.title || document.title);
}

function pagurePullRequestAuthor(route) {
  var heading = pagurePullRequestHeading(route);
  var opened = heading && Array.prototype.slice.call(heading.querySelectorAll(".font-weight-bold, strong")).find(function(node) {
    return /^Opened$/i.test(normalizeText(node.textContent));
  });
  var status = opened && opened.closest("small");
  var sibling = opened && opened.parentElement && opened.parentElement.nextElementSibling;
  while (sibling && status && status.contains(sibling)) {
    var siblingText = normalizeText(sibling.textContent);
    var siblingMatch = siblingText.match(/^by\s+(.+?)[.]?$/i);
    if (siblingMatch) {
      var titledAuthor = /^by\s+/i.test(siblingText) && normalizeText(sibling.getAttribute("title"));
      return (titledAuthor || siblingMatch[1]).replace(/[.,;:!?]+$/, "");
    }
    sibling = sibling.nextElementSibling;
  }

  var statusText = normalizeText(status && status.textContent);
  var openedIndex = statusText.search(/\bOpened\b/i);
  var match = openedIndex >= 0 && statusText.slice(openedIndex).match(/\bOpened\b[\s\S]*?\bby\s+@?([^\s.,;:!?]+)/i);
  return match ? match[1] : "";
}

function pagurePullRequestEntry(node, route) {
  var markdown = pagureNodeMarkdown(node);
  if (!normalizeText(markdown)) return null;
  var event = !node.matches(".card") &&
    (node.matches(".autogenerated-comment") || !!node.querySelector(".autogenerated-comment"));
  var clone = visibilityPrunedClone(node);
  removeAll(clone, "button, form, [role='tooltip'], .issue_actions, .issue_reactions, .comment-reactions");
  var header = node.querySelector(".card-header");
  var inlineContext = header && header.querySelector(".inline_comment_link_btn");
  var inlineText = normalizeText(inlineContext && inlineContext.textContent);
  var context = /^\d+\s+of\s+.+$/i.test(inlineText) ? "on line " + inlineText : "";
  return {
    sourceNode: clone,
    kind: event ? "Event" : "Comment",
    author: pagureIssueAuthor(node),
    context: context,
    markdown: markdown,
    permalink: event ? null : pagureThreadPermalink(node, route.pullPath),
    timestamp: pagureIssueTimestamp(node)
  };
}

function pagurePullRequestEntries(root, route) {
  var section = root.querySelector("section.request_comment");
  if (!section) return [];
  var container = section.querySelector(":scope > form") || section;
  var entries = Array.prototype.slice.call(container.children).filter(function(node) {
    if (elementSubtreeHidden(node)) return false;
    return node.matches(".card, .autogenerated-comment") || !!node.querySelector(".autogenerated-comment");
  }).map(function(node) {
    return pagurePullRequestEntry(node, route);
  });
  return deduplicateForgeThreadPermalinks(entries);
}

function pagurePullRequestPatchUrl(route) {
  var expected = new Set([
    route.pullPath + ".patch",
    route.pullPath + "/" + route.number + ".patch"
  ]);
  var link = Array.prototype.slice.call(document.querySelectorAll("a[href]")).find(function(candidate) {
    try {
      var url = new URL(candidate.getAttribute("href"), location.href);
      return url.origin === location.origin && expected.has(url.pathname);
    } catch (_error) {
      return false;
    }
  });
  return link ? materializedHttpUrl(link.getAttribute("href")) : null;
}

function pagurePullRequestInventory(route) {
  var entries = [
    { label: "Project", url: location.origin + route.basePath },
    { label: "Issues", url: location.origin + route.basePath + "/issues" },
    { label: "Pull requests", url: location.origin + route.basePath + "/pull-requests" },
    { label: "Pull request page", url: location.origin + route.pullPath }
  ];
  var patch = pagurePullRequestPatchUrl(route);
  if (patch) entries.push({ label: "Patch", url: patch });
  entries.push({
    label: "Pull request API",
    url: location.origin + route.apiPrefix + "/" + route.projectPath + "/pull-request/" + route.number,
    detail: "When enabled. Static archives and some installations may not expose this route."
  });
  return browsableInventory("Browse this Pagure pull request", entries);
}

function pagurePullRequestContent(metadata) {
  var route = pagurePullRequestRoute();
  if (!route) return null;
  var root = pagurePullRequestRoot();
  if (!pagurePullRequestProductMatch(route, root)) return null;
  var opening = pagurePullRequestOpening(root);
  var title = pagurePullRequestTitle(route, metadata);
  if (!opening || !title) return null;

  var openingMarkdown = pagureNodeMarkdown(opening);
  var author = pagurePullRequestAuthor(route);
  var entries = pagurePullRequestEntries(root, route);
  var archive = pagureArchiveNotice();
  var pullMetadata = pagureThreadMetadata(root);
  var sections = ["# " + title, "- Pull request: " + route.community];
  if (author) sections.push("- Author: " + author);
  if (archive) sections.push("## Archive status", archive.markdown);
  var openingUrl = location.origin + route.pullPath + (opening.querySelector("#comment-0") ? "#comment-0" : "");
  sections.push("## " + markdownLink("Opening", openingUrl));
  if (openingMarkdown) sections.push(openingMarkdown);
  if (pullMetadata) sections.push("## Metadata", pullMetadata.markdown);
  if (entries.length) sections.push("## Timeline");
  sections = sections.concat(pagureThreadEntrySections(entries));
  sections.push(pagurePullRequestInventory(route));

  var visibleNodes = [visibilityPrunedClone(opening)].concat(entries.map(function(entry) {
    return entry.sourceNode;
  }));
  if (pullMetadata) visibleNodes.push(pullMetadata.node);
  if (archive) visibleNodes.push(archive.node);
  return {
    title: title,
    byline: author,
    excerpt: normalizeText(openingMarkdown),
    siteName: "Pagure",
    publishedTime: pagureIssueTimestamp(opening) || metadata.publishedTime,
    html: visibleNodes.filter(Boolean).map(function(node) { return node.outerHTML; }).join("\n"),
    markdown: sections.filter(Boolean).join("\n\n"),
    textContent: normalizeText([title, openingMarkdown].concat(entries.map(function(entry) {
      return entry.markdown;
    })).join(" ")),
    hostAware: true,
    readerMode: false,
    contentType: "social",
    socialKind: "thread",
    threadConversation: true,
    platform: "Pagure",
    handle: author,
    replyCount: null,
    community: route.community
  };
}

function registerPagurePullRequestProfiles() {
  registerHostAwareProfile(true, pagurePullRequestContent);
}
