function gerritChangeMessages(prepared) {
  return (Array.isArray(prepared.detail.messages) ? prepared.detail.messages : []).map(function(message, index) {
    return {
      kind: /^autogenerated:/i.test(normalizeText(message.tag)) ? "Event" : "Change message",
      author: gerritAccountName(message.author || message.real_author),
      timestamp: normalizeText(message.date),
      patchset: normalizeText(message._revision_number),
      message: String(message.message || ""),
      id: normalizeText(message.id),
      sourceOrder: index
    };
  });
}

function gerritInlineComments(collection, kind, sourceOffset) {
  var records = [];
  Object.keys(collection || {}).forEach(function(filePath, fileIndex) {
    var comments = Array.isArray(collection[filePath]) ? collection[filePath] : [];
    comments.forEach(function(comment, commentIndex) {
      records.push({
        kind: comment.robot_id || comment.robot_run_id ? "Robot comment" : kind,
        author: gerritAccountName(comment.author || comment.real_author),
        timestamp: normalizeText(comment.updated),
        patchset: normalizeText(comment.patch_set),
        message: String(comment.message || ""),
        id: normalizeText(comment.id),
        filePath: filePath,
        line: comment.line,
        range: comment.range || null,
        side: normalizeText(comment.side),
        parent: normalizeText(comment.parent),
        unresolved: comment.unresolved,
        inReplyTo: normalizeText(comment.in_reply_to),
        contextLines: Array.isArray(comment.context_lines) ? comment.context_lines : [],
        robotId: normalizeText(comment.robot_id),
        robotRunId: normalizeText(comment.robot_run_id),
        sourceOrder: sourceOffset + fileIndex * 1000000 + commentIndex
      });
    });
  });
  return records;
}

function gerritTimelineRecords(prepared) {
  var messages = gerritChangeMessages(prepared);
  var comments = gerritInlineComments(prepared.comments, "Inline comment", messages.length);
  return messages.concat(comments).sort(function(left, right) {
    var leftTime = Date.parse(left.timestamp);
    var rightTime = Date.parse(right.timestamp);
    if (!isNaN(leftTime) && !isNaN(rightTime) && leftTime !== rightTime) return leftTime - rightTime;
    if (!isNaN(leftTime) && isNaN(rightTime)) return -1;
    if (isNaN(leftTime) && !isNaN(rightTime)) return 1;
    return left.sourceOrder - right.sourceOrder;
  });
}

function gerritCommentLocation(record, prepared) {
  if (!record.filePath) return "";
  var label = record.filePath;
  if (record.range) {
    label += ":" + [record.range.start_line, record.range.start_character].join(":") + "-" +
      [record.range.end_line, record.range.end_character].join(":");
  } else if (record.line != null) {
    label += ":" + record.line;
  }
  var url = gerritChangeFileUiUrl(prepared, record.filePath, record.patchset);
  return url ? markdownLink(label, url) : label;
}

function gerritContextMarkdown(contextLines) {
  if (!Array.isArray(contextLines) || !contextLines.length) return "";
  return contextLines.map(function(line) {
    return "    " + normalizeText(line.line_number) + " | " + String(line.context_line || "");
  }).join("\n");
}

function gerritTimelineSections(records, prepared) {
  var sections = [];
  records.forEach(function(record) {
    sections.push("### " + record.kind + (record.author ? " by " + record.author : ""));
    if (record.timestamp) sections.push("- Time: " + record.timestamp);
    if (record.patchset) sections.push("- Patch set: " + record.patchset);
    if (record.side) sections.push("- Side: " + record.side);
    if (record.parent) sections.push("- Parent: " + record.parent);
    if (record.id) sections.push("- Record ID: " + record.id);
    if (record.filePath) sections.push("- Location: " + gerritCommentLocation(record, prepared));
    if (record.unresolved != null) sections.push("- Status: " + (record.unresolved ? "Unresolved" : "Resolved"));
    if (record.inReplyTo) sections.push("- In reply to: " + record.inReplyTo);
    if (record.robotId) sections.push("- Robot: " + record.robotId);
    if (record.robotRunId) sections.push("- Robot run: " + record.robotRunId);
    if (record.message) sections.push(gerritLiteralBlock(record.message));
    var context = gerritContextMarkdown(record.contextLines);
    if (context) sections.push("#### Context", context);
  });
  return sections;
}

function gerritLabelSections(detail) {
  var labels = detail.labels || {};
  var sections = [];
  Object.keys(labels).forEach(function(labelName) {
    sections.push("### " + labelName);
    var votes = Array.isArray(labels[labelName].all) ? labels[labelName].all : [];
    if (votes.length) {
      votes.forEach(function(vote) {
        var name = gerritAccountName(vote) || "Unknown account";
        var value = Number(vote.value);
        sections.push("- " + name + ": " + (value > 0 ? "+" : "") + value);
      });
    } else {
      sections.push("- No detailed votes returned.");
    }
  });
  return sections;
}

function gerritFileSections(prepared) {
  var sections = [];
  Object.keys(prepared.files || {}).forEach(function(filePath) {
    var file = prepared.files[filePath] || {};
    var url = gerritChangeFileUiUrl(prepared, filePath);
    sections.push("### " + (url ? markdownLink(filePath, url) : filePath));
    if (file.status) sections.push("- Status: " + file.status);
    if (file.old_path) sections.push("- Previous path: " + file.old_path);
    if (file.lines_inserted != null) sections.push("- Lines inserted: " + file.lines_inserted);
    if (file.lines_deleted != null) sections.push("- Lines deleted: " + file.lines_deleted);
    if (file.size_delta != null) sections.push("- Size delta: " + file.size_delta);
    if (file.size != null) sections.push("- Size: " + file.size);
    if (file.binary) sections.push("- Binary: yes");
  });
  return sections;
}
