function pagureIssueOpening(root) {
  return root.querySelector("#original_comment_box #comment-0, #comment-0.issue_comment");
}

function pagureIssueEntry(node, route) {
  var markdown = pagureNodeMarkdown(node);
  if (!normalizeText(markdown)) return null;
  var event = !node.matches(".card") &&
    (node.matches(".autogenerated-comment") || !!node.querySelector(".autogenerated-comment"));
  var clone = visibilityPrunedClone(node);
  removeAll(clone, "button, form, [role='tooltip'], .issue_actions, .issue_reactions, .comment-reactions");
  return {
    sourceNode: clone,
    kind: event ? "Event" : "Comment",
    author: pagureIssueAuthor(node),
    markdown: markdown,
    permalink: event ? null : pagureIssuePermalink(node, route),
    timestamp: pagureIssueTimestamp(node)
  };
}

function pagureIssueEntries(root, route) {
  var comments = root.querySelector("#comments");
  if (!comments) return [];
  var entries = Array.prototype.slice.call(comments.children).filter(function(node) {
    if (elementSubtreeHidden(node)) return false;
    return node.matches(".card, .autogenerated-comment") || !!node.querySelector(".autogenerated-comment");
  }).map(function(node) {
    return pagureIssueEntry(node, route);
  });
  return deduplicateForgeThreadPermalinks(entries);
}

function pagureIssueTitle(root, route, metadata) {
  var heading = pagureIssueHeading(root, route);
  var primary = heading && heading.querySelector(":scope > div");
  var title = normalizeText((primary || heading || {}).textContent || "")
    .replace(new RegExp("^#" + route.number + "\\s*"), "");
  return title || normalizeText(metadata.title || document.title);
}

function pagureIssueOpeningAuthor(root, route) {
  var heading = pagureIssueHeading(root, route);
  var authorText = heading && Array.prototype.slice.call(heading.querySelectorAll("small span"))
    .map(function(node) {
      return normalizeText(node.textContent);
    }).find(function(text) {
      return /^by\s+@?[\w.-]+\.?$/i.test(text);
    });
  var authorMatch = authorText && authorText.match(/^by\s+@?([\w.-]+)/i);
  if (authorMatch) return authorMatch[1].replace(/[.,;:!?]+$/, "");
  var author = heading && heading.querySelector("[data-testid='author']");
  return normalizeText(author && author.textContent);
}

function pagureIssueContent(metadata) {
  var route = pagureIssueRoute();
  if (!route) return null;
  var root = pagureIssueRoot();
  if (!pagureProductMatch(route, root)) return null;
  var opening = pagureIssueOpening(root);
  var title = pagureIssueTitle(root, route, metadata);
  if (!opening || !title) return null;

  var openingMarkdown = pagureNodeMarkdown(opening);
  var author = pagureIssueOpeningAuthor(root, route);
  var entries = pagureIssueEntries(root, route);
  var archive = pagureArchiveNotice();
  var issueMetadata = pagureThreadMetadata(root);
  var sections = ["# " + title, "- Issue: " + route.community];
  if (author) sections.push("- Author: " + author);
  if (archive) sections.push("## Archive status", archive.markdown);
  sections.push("## " + markdownLink("Opening", location.origin + route.issuePath + "#comment-0"));
  if (openingMarkdown) sections.push(openingMarkdown);
  if (issueMetadata) sections.push("## Metadata", issueMetadata.markdown);
  if (entries.length) sections.push("## Timeline");
  sections = sections.concat(pagureThreadEntrySections(entries));
  sections.push(pagureIssueInventory(route));

  var visibleNodes = [visibilityPrunedClone(opening)].concat(entries.map(function(entry) {
    return entry.sourceNode;
  }));
  if (issueMetadata) visibleNodes.push(issueMetadata.node);
  if (archive) visibleNodes.push(archive.node);
  return {
    title: title,
    byline: author,
    excerpt: normalizeText(openingMarkdown),
    siteName: "Pagure",
    publishedTime: pagureIssueTimestamp(root) || metadata.publishedTime,
    html: visibleNodes.filter(Boolean).map(function(node) { return node.outerHTML; }).join("\n"),
    markdown: sections.filter(Boolean).join("\n\n"),
    textContent: normalizeText([title, openingMarkdown].concat(entries.map(function(entry) {
      return entry.markdown;
    })).join(" ")),
    hostAware: true,
    readerMode: false,
    contentType: "social",
    socialKind: "thread",
    threadConversation: true,
    platform: "Pagure",
    handle: author,
    replyCount: null,
    community: route.community
  };
}

function registerPagureThreadProfiles() {
  registerHostAwareProfile(true, pagureIssueContent);
}
